### ISSUE TITLE
Request: Unmaintained Project: Remove from Pypi.org

### ISSUE THREAD

**Issue by jeff00seattle** [sdvillal/jagged#7]
Promising project for my needs, but it has not been maintained for over 2 years:
```bash
$ python3 --version
Python 3.5.4
$ python3 -m pip install jagged
Collecting jagged
  Using cached https://files.pythonhosted.org/packages/4a/df/9eb13cee1df8a2694f5a6a5997c447242c64edf7f95017c7466d69162104/jagged-0.1.0.tar.gz
Collecting future (from jagged)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from jagged) (1.14.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from jagged) (0.23.0)
Collecting whatami>=4.0.0 (from jagged)
  Using cached https://files.pythonhosted.org/packages/aa/1d/f9af2ce40d3e8734af5d844e92cdd78617a955628f97b3b9db8a365be4bc/whatami-5.1.15.tar.gz
Collecting toolz (from jagged)
  Using cached https://files.pythonhosted.org/packages/14/d0/a73c15bbeda3d2e7b381a36afb0d9cd770a9f4adc5d1532691013ba881db/toolz-0.9.0.tar.gz
Collecting blosc (from jagged)
  Using cached https://files.pythonhosted.org/packages/bc/c1/a61ee9b605ceee140a638f70734be44c489ad919ba6fb698d18239baa8b2/blosc-1.5.1.tar.gz
Collecting bloscpack (from jagged)
  Using cached https://files.pythonhosted.org/packages/20/ad/c8b6018e3290bad030d09c98676fa9d4c4d70bcbae30aac4ff7422651f8f/bloscpack-0.12.0-py3-none-any.whl
Collecting bcolz (from jagged)
  Using cached https://files.pythonhosted.org/packages/5c/4e/23942de9d5c0fb16f10335fa83e52b431bcb8c0d4a8419c9ac206268c279/bcolz-1.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    Couldn't find index page for 'setuptools-scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:719) -- Some packages may not be found!
    No local packages or working download links found for setuptools-scm>1.5.4
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rc/6df01x69477gsyrjzvg58bnm0000gp/T/pip-install-8aw727o7/bcolz/setup.py", line 234, in <module>
        cmdclass=LazyCommandClass(),
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm>1.5.4')
    SSE2 detected
    AVX2 detected

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rc/6df01x69477gsyrjzvg58bnm0000gp/T/pip-install-8aw727o7/bcolz/
```

**Comment by sdvillal** [comment]
Thanks for your interest. I have just installed in python 3.6 and works well. These messages seem more related to your environment. Maybe ```pip install  setuptools-scm```?
